# Generated by Django 6.0.4 on 2026-04-26 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yazi',
            name='yazar',
        ),
        migrations.AddField(
            model_name='yazi',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now_add=True, default='2026-04-26'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kategori',
            name='ust_kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategoriler', to='icerik.kategori'),
        ),
    ]
